### ISSUE TITLE
[Refactor] 전체 리팩토링

### ISSUE THREAD

**Issue by kj9470** [Team-Puzzling/Puzzling_iOS#68]
## 🧩 이슈 요약

- 컨벤션 체크

## ✅ 체크 리스트

- [ ] 컨벤션 체크

**Comment by ahra1221** [comment]
정아 보고십따 넌 최고야.

**Comment by kj9470** [comment]
보고 싶어 ~~~~~~~~~~~~~~~~~~~~고아라 ~~~~~~~~~~~₩₩
